### ISSUE TITLE
Searching in queries for SQL keywords might crash

### ISSUE THREAD

**Issue by pgab** [GiGainfosystems/diesel-oci#7]
We have several places where we search for SQL keywords, e.g. https://github.com/GiGainfosystems/diesel-oci/blob/feature/more_gst_compat/src/oracle/connection/stmt.rs#L29

This can go wrong for statements like `UPDATE table SET k='LIMIT';`. Once we can override the default limit clause of diesel with e.g https://github.com/rust-lang/rfcs/pull/2451#issuecomment-411890494 we can implement a more idiomatic way to generate the proper SQL.

**Comment by geomaniac** [comment]
We could mitigate some of those with statement attributes. E.g. checking if a statement is `SELECT` or `INSERT`. This however won's fix the `LIMIT` and `RETURNING` issues.

E.G. `OCI_ATTR_STMT_TYPE` or `OCI_ATTR_SQLFNCODE`.

**Comment by geomaniac** [comment]
fixed with #25 and #26
